fconc: fconc.o readwrite.o writefile.o
	        gcc -o fconc fconc.o readwrite.o writefile.o

fconc.o: fconc.c
	        gcc -Wall -c fconc.c

readwrite.o: readwrite.c
	        gcc -Wall -c readwrite.c

writefile.o: writefile.c
	        gcc -Wall -c writefile.c
